
services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: _postgres_
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant/storage:/qdrant/storage:z
    restart: unless-stopped

  engine:
    image: onionkim/sharebot-engine:1.0
    container_name: engine
    ports:
      - "6010:6010"
    env_file:
      - ./engine/.env.docker
    depends_on:
      - qdrant
    restart: unless-stopped

  back:
    image: onionkim/sharebot-back:1.0
    container_name: sharebot-back
    ports:
      - "6020:6020"
    env_file:
      - ./sharebot-back/.env.docker
    depends_on:
      - engine
      - db
    restart: unless-stopped

  front:
    image: onionkim/sharebot-front:1.0
    container_name: sharebot-front
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata: